# Generated by Django 3.0.7 on 2020-06-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noterler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noterler',
            name='noterFaksi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='noterler',
            name='noterSinifi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='noterler',
            name='noterlikSinifi',
            field=models.IntegerField(),
        ),
    ]
